apiVersion: v1
kind: Pod
metadata:
  name: go-demo-multicontainer
spec:
  containers:
    - name: go-demo-app
      image: denvazh/go-demo-app:latest
      ports:
        - containerPort: 8080
    - name: sidecar
      image: busybox
      command: ["sh", "-c", "while true; do echo sidecar running; sleep 30; done"]
