apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-demo-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: go-demo-app
              image: denvazh/go-demo-app:latest
          restartPolicy: OnFailure
